In [1]:
!pip install numpy

You should consider upgrading via the 'c:\users\admin\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [2]:
!pip install pandas

You should consider upgrading via the 'c:\users\admin\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [3]:
!pip install matplotlib

You should consider upgrading via the 'c:\users\admin\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [4]:
!pip install seaborn

You should consider upgrading via the 'c:\users\admin\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [5]:
!pip install sklearn

Using legacy setup.py install for sklearn, since package 'wheel' is not installed.
    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'


You should consider upgrading via the 'c:\users\admin\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('heart.csv')

In [8]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [14]:
df = df.sample(frac=1)

In [15]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
178   43    1   0       120   177    0        0      120      1      2.5   
236   58    1   0       125   300    0        0      171      0      0.0   
222   65    1   3       138   282    1        0      174      0      1.4   
82    60    0   2       102   318    0        1      160      0      0.0   
119   46    0   0       138   243    0        0      152      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
23    61    1   2       150   243    1        1      137      1      1.0   
12    49    1   1       130   266    0        1      171      0      0.6   
46    44    1   2       140   235    0        0      180      0      0.0   
15    50    0   2       120   219    0        1      158      0      1.6   
73    51    1   0       140   261    0        0      186      1      0.0   

     slope  ca  thal  target  
178      1   0     3       0  
236      2   2     3       0  
222      1   1     2       0  
82       2   1     2       1  
119      1   0     2       1  
..     ...  ..   ...     ...  
23       1   0     2       1  
12       2   0     2       1  
46       2   0     2       1  
15       1   0     2       1  
73       2   0     2       1  

[303 rows x 14 columns]

In [19]:
X = df.drop(['target'], axis=1).values
Y = df['target'].values

In [18]:
X

array([[43.,  1.,  0., ...,  1.,  0.,  3.],
       [58.,  1.,  0., ...,  2.,  2.,  3.],
       [65.,  1.,  3., ...,  1.,  1.,  2.],
       ...,
       [44.,  1.,  2., ...,  2.,  0.,  2.],
       [50.,  0.,  2., ...,  1.,  0.,  2.],
       [51.,  1.,  0., ...,  2.,  0.,  2.]])

In [20]:
Y

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=64) 

In [22]:
knn = KNeighborsClassifier()

In [23]:
knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [24]:
Y_pred = knn.predict(X_test)

In [25]:
Y_pred

array([1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int64)

In [26]:
accuracy_score(Y_pred, Y_test)

0.6710526315789473

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
std = StandardScaler()
X_train_scaled = std.fit_transform(X_train)

In [29]:
X_test_scaled = std.transform(X_test)

In [30]:
knn.fit(X_train_scaled, Y_train)

KNeighborsClassifier()

In [31]:
Y_pred = knn.predict(X_test_scaled)

In [32]:
accuracy_score(Y_test, Y_pred )

0.8289473684210527